services:
  server:
    build: .
    ports:
      - "10568:10568"
    platform: linux/amd64
    stop_signal: SIGKILL
  web:
    build:
      context: .
      dockerfile_inline: |
        FROM davesilva/godot-ci:3.5.3 AS build
        WORKDIR /root
        RUN mkdir -p /root/build
        COPY . /root
        RUN godot --no-window --verbose --export "HTML5" build/index.html

        FROM nginx AS run
        WORKDIR /usr/share/nginx/html
        COPY --from=build /root/build .
        COPY web/multiplayer_test.html ./multitest/index.html
    ports:
      - "8080:8080"
    platform: linux/amd64
    configs:
      - source: nginx-default.conf
        target: /etc/nginx/conf.d/default.conf
configs:
  nginx-default.conf:
    content: |
      server {
        listen       8080;
        server_name  localhost;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
      }
